### ISSUE TITLE
bug: from graphviz import * error 

### ISSUE THREAD

**Issue by atomsos** [xflr6/graphviz#167]
For version 0.19.1, 0.19, if I run
```python
from graphviz import *
```

then 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'graphviz' has no attribute 'ExecutableNotFound, CalledProcessError'
```

but for 0.18, everything is OK. Is this a bug?

**Comment by xflr6** [comment]
Thanks for the report.

It's a bug, broken in https://github.com/xflr6/graphviz/commit/b0898c5f47d4ddfe8a138f5af440bf1e94554a29#diff-60d8e275820dc7875c1c88834b746ee2c92d64f97d04b96ef2ac49d4375a1ba0R53.

Pending fix in 8cda190a9cb9890828bf032c18524aa8dc8ec2a2.

**Comment by xflr6** [comment]
Fixed in [`0.19.2` release](https://pypi.org/project/graphviz/0.19.2/#files), closing.
